/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package berkay;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;

/**
 *
 * @author Berkay
 */
public class film_screen_2 extends javax.swing.JFrame {

    /**
     * Creates new form film_screen_2
     */
    public film_screen_2() {
        initComponents();
        ImageIcon img=new ImageIcon("C:\\Users\\Berkay\\Desktop\\berkay\\src\\berkay\\Netflix_logo_n.png");
        this.setIconImage(img.getImage());
    }
    static final String JDBC_DRIVER="com.mysql.jdbc.Driver";
    static final String DOMAIN_NAME="root";
    static final String DB_NAME="project";
    static final String DB_URL="jdbc:mysql://"+DOMAIN_NAME+"/"+DB_NAME;
    static final String USER="root";
    static final String PASS="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        interstellar = new javax.swing.JLabel();
        bizihatirla = new javax.swing.JLabel();
        criminal = new javax.swing.JLabel();
        dangal = new javax.swing.JLabel();
        davincicode = new javax.swing.JLabel();
        delibal = new javax.swing.JLabel();
        frankestein = new javax.swing.JLabel();
        jaws = new javax.swing.JLabel();
        strangerthings = new javax.swing.JLabel();
        theblacklist = new javax.swing.JLabel();
        theoriginals = new javax.swing.JLabel();
        b_interstellar = new javax.swing.JButton();
        b_bizihatirla = new javax.swing.JButton();
        b_criminal = new javax.swing.JButton();
        b_dangal = new javax.swing.JButton();
        b_davincicode = new javax.swing.JButton();
        b_delibal = new javax.swing.JButton();
        b_frankestein = new javax.swing.JButton();
        b_jaws = new javax.swing.JButton();
        b_strangerthings = new javax.swing.JButton();
        b_blacklist = new javax.swing.JButton();
        b_theoriginals = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        interstellar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berkay/interstellar.jpg"))); // NOI18N

        bizihatirla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berkay/bizihatırla.jpg"))); // NOI18N

        criminal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berkay/criminal.jpg"))); // NOI18N

        dangal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berkay/dangal.jpg"))); // NOI18N

        davincicode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berkay/davincicode.jpg"))); // NOI18N

        delibal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berkay/delibal.jpg"))); // NOI18N

        frankestein.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berkay/frankestein.jpg"))); // NOI18N

        jaws.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berkay/jaws.jpg"))); // NOI18N

        strangerthings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berkay/strangerthings.jpg"))); // NOI18N

        theblacklist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berkay/theblacklist.jpg"))); // NOI18N

        theoriginals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berkay/theoriginal.jpg"))); // NOI18N

        b_interstellar.setText("İZLE");
        b_interstellar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_interstellarActionPerformed(evt);
            }
        });

        b_bizihatirla.setText("İZLE");
        b_bizihatirla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_bizihatirlaActionPerformed(evt);
            }
        });

        b_criminal.setText("İZLE");
        b_criminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_criminalActionPerformed(evt);
            }
        });

        b_dangal.setText("İZLE");
        b_dangal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_dangalActionPerformed(evt);
            }
        });

        b_davincicode.setText("İZLE");
        b_davincicode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_davincicodeActionPerformed(evt);
            }
        });

        b_delibal.setText("İZLE");
        b_delibal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_delibalActionPerformed(evt);
            }
        });

        b_frankestein.setText("İZLE");
        b_frankestein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_frankesteinActionPerformed(evt);
            }
        });

        b_jaws.setText("İZLE");
        b_jaws.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_jawsActionPerformed(evt);
            }
        });

        b_strangerthings.setText("İZLE");
        b_strangerthings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_strangerthingsActionPerformed(evt);
            }
        });

        b_blacklist.setText("İZLE");
        b_blacklist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_blacklistActionPerformed(evt);
            }
        });

        b_theoriginals.setText("İZLE");
        b_theoriginals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_theoriginalsActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berkay/search.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Arama Yapmak İçin İkona Tıklayın");

        jButton1.setText("ÖNCEKİ SAYFA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(strangerthings)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(theblacklist))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(davincicode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delibal))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(interstellar)
                                .addGap(27, 27, 27)
                                .addComponent(bizihatirla)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(criminal)
                                    .addComponent(frankestein))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jaws)
                                    .addComponent(dangal)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(theoriginals)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(jButton1))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(b_interstellar)
                        .addGap(171, 171, 171)
                        .addComponent(b_bizihatirla)
                        .addGap(166, 166, 166)
                        .addComponent(b_criminal)
                        .addGap(182, 182, 182)
                        .addComponent(b_dangal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(b_davincicode)
                        .addGap(176, 176, 176)
                        .addComponent(b_delibal)
                        .addGap(167, 167, 167)
                        .addComponent(b_frankestein)
                        .addGap(177, 177, 177)
                        .addComponent(b_jaws))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(b_strangerthings)
                        .addGap(185, 185, 185)
                        .addComponent(b_blacklist)
                        .addGap(161, 161, 161)
                        .addComponent(b_theoriginals)))
                .addContainerGap(945, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dangal)
                    .addComponent(criminal)
                    .addComponent(bizihatirla)
                    .addComponent(interstellar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_interstellar)
                    .addComponent(b_bizihatirla)
                    .addComponent(b_criminal)
                    .addComponent(b_dangal))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(davincicode)
                    .addComponent(delibal)
                    .addComponent(frankestein)
                    .addComponent(jaws))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_davincicode)
                    .addComponent(b_delibal)
                    .addComponent(b_frankestein)
                    .addComponent(b_jaws))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(strangerthings)
                    .addComponent(theblacklist)
                    .addComponent(theoriginals)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_strangerthings)
                    .addComponent(b_blacklist)
                    .addComponent(b_theoriginals))
                .addContainerGap(1426, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_interstellarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_interstellarActionPerformed
        // TODO add your handling code here:
        Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_f wsf=new watch_screen_f();
        film_screen fs=new film_screen();
        fs.name_c.add("INTERSTELLAR");
        Connection conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,21);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
            System.out.println(line);
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                System.out.println("j="+j);
                System.out.println(line);
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    System.out.println("kontrol");
                    System.out.println(pid);
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==21){
                    System.out.println("giriyooo");
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsf.setVisible(true);
                    break;
                    
                }
                
                control1++;
             
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println("oldu");
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,21);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
                
                
                
            }
               
            } 
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_b_interstellarActionPerformed

    private void b_bizihatirlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_bizihatirlaActionPerformed
        // TODO add your handling code here:
                Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_f wsf=new watch_screen_f();
        film_screen fs=new film_screen();
        fs.name_c.add("BİZİ HATIRLA");
        Connection conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,22);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
            System.out.println(line);
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                System.out.println("j="+j);
                System.out.println(line);
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    System.out.println("kontrol");
                    System.out.println(pid);
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==22){
                    System.out.println("giriyooo");
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsf.setVisible(true);
                    break;
                    
                }
                
                control1++;
             
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println("oldu");
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,22);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
                
                
                
            }
               
            } 
            
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_b_bizihatirlaActionPerformed

    private void b_criminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_criminalActionPerformed
        // TODO add your handling code here:
        Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_d wsd=new watch_screen_d();
        film_screen fs=new film_screen();
        fs.name_c.add("Criminal");
        fs.dizi_time.add(40);
        fs.dizi_part.add(10);
        System.out.println("");
        Connection conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,27);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
                System.out.println("Burda");
            System.out.println(line);
                System.out.println(sis.user.get(0));
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==27){
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsd.setVisible(true);
                    break;
                    
                }
                
                control1++;
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,27);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
        
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
                
                
                
            }
               
            }
            
            
        } catch (Exception e) {
        }
        
        
        
    }//GEN-LAST:event_b_criminalActionPerformed

    private void b_dangalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_dangalActionPerformed
        // TODO add your handling code here:
         Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_f wsf=new watch_screen_f();
        film_screen fs=new film_screen();
        fs.name_c.add("DANGAL");
        Connection conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,24);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
            System.out.println(line);
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                System.out.println("j="+j);
                System.out.println(line);
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    System.out.println("kontrol");
                    System.out.println(pid);
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==24){
                    System.out.println("giriyooo");
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsf.setVisible(true);
                    break;
                    
                }
                
                control1++;
             
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println("oldu");
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,24);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
                
                
                
            }
               
            } 
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_b_dangalActionPerformed

    private void b_davincicodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_davincicodeActionPerformed
        // TODO add your handling code here:
         Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_f wsf=new watch_screen_f();
        film_screen fs=new film_screen();
        fs.name_c.add("DA VİNCİ CODE");
        Connection conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,26);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
            System.out.println(line);
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                System.out.println("j="+j);
                System.out.println(line);
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    System.out.println("kontrol");
                    System.out.println(pid);
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==26){
                    System.out.println("giriyooo");
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsf.setVisible(true);
                    break;
                    
                }
                
                control1++;
             
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println("oldu");
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,26);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
                
                
                
            }
               
            } 
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_b_davincicodeActionPerformed

    private void b_delibalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_delibalActionPerformed
        // TODO add your handling code here:
         Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_f wsf=new watch_screen_f();
        film_screen fs=new film_screen();
        fs.name_c.add("DELİBAL");
        Connection conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,23);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
            System.out.println(line);
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                System.out.println("j="+j);
                System.out.println(line);
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    System.out.println("kontrol");
                    System.out.println(pid);
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==23){
                    System.out.println("giriyooo");
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsf.setVisible(true);
                    break;
                    
                }
                
                control1++;
             
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println("oldu");
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,23);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
                
                
                
            }
               
            } 
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_b_delibalActionPerformed

    private void b_frankesteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_frankesteinActionPerformed
        // TODO add your handling code here:
         Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_f wsf=new watch_screen_f();
        film_screen fs=new film_screen();
        fs.name_c.add("FRANKESTEIN");
        Connection conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,29);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
            System.out.println(line);
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                System.out.println("j="+j);
                System.out.println(line);
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    System.out.println("kontrol");
                    System.out.println(pid);
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==29){
                    System.out.println("giriyooo");
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsf.setVisible(true);
                    break;
                    
                }
                
                control1++;
             
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println("oldu");
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,29);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
                
                
                
            }
               
            } 
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_b_frankesteinActionPerformed

    private void b_jawsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_jawsActionPerformed
        // TODO add your handling code here:
         Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_f wsf=new watch_screen_f();
        film_screen fs=new film_screen();
        fs.name_c.add("JAWS");
        Connection conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,25);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
            System.out.println(line);
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                System.out.println("j="+j);
                System.out.println(line);
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    System.out.println("kontrol");
                    System.out.println(pid);
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==25){
                    System.out.println("giriyooo");
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsf.setVisible(true);
                    break;
                    
                }
                
                control1++;
             
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println("oldu");
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,25);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
                
                
                
            }
               
            } 
            
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_b_jawsActionPerformed

    private void b_strangerthingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_strangerthingsActionPerformed
        // TODO add your handling code here:
         Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_d wsd=new watch_screen_d();
        film_screen fs=new film_screen();
        fs.name_c.add("Stranger Things");
        fs.dizi_time.add(40);
        fs.dizi_part.add(10);
        System.out.println("");
        Connection conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,30);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
                System.out.println("Burda");
            System.out.println(line);
                System.out.println(sis.user.get(0));
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==30){
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsd.setVisible(true);
                    break;
                    
                }
                
                control1++;
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,30);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
        
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
                
                
                
            }
               
            }
            
            
        } catch (Exception e) {
        }
        
        
        
    }//GEN-LAST:event_b_strangerthingsActionPerformed

    private void b_blacklistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_blacklistActionPerformed
        // TODO add your handling code here:
         Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_d wsd=new watch_screen_d();
        film_screen fs=new film_screen();
        fs.name_c.add("The Blacklist");
        fs.dizi_time.add(40);
        fs.dizi_part.add(10);
        System.out.println("");
        Connection conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,28);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
                System.out.println("Burda");
            System.out.println(line);
                System.out.println(sis.user.get(0));
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==28){
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsd.setVisible(true);
                    break;
                    
                }
                
                control1++;
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,28);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
        
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
                
                
                
            }
               
            }
            
            
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_b_blacklistActionPerformed

    private void b_theoriginalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_theoriginalsActionPerformed
        // TODO add your handling code here:
         Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_d wsd=new watch_screen_d();
        film_screen fs=new film_screen();
        fs.name_c.add("The Originals");
        fs.dizi_time.add(40);
        fs.dizi_part.add(10);
        System.out.println("");
        Connection conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,31);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
                System.out.println("Burda");
            System.out.println(line);
                System.out.println(sis.user.get(0));
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==31){
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsd.setVisible(true);
                    break;
                    
                }
                
                control1++;
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,31);
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
        
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
                
                
                
            }
               
            }
            
            
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_b_theoriginalsActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        search s=new search();
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        film_screen fs=new film_screen();
        this.setVisible(false);
        fs.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(film_screen_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(film_screen_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(film_screen_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(film_screen_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new film_screen_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_bizihatirla;
    private javax.swing.JButton b_blacklist;
    private javax.swing.JButton b_criminal;
    private javax.swing.JButton b_dangal;
    private javax.swing.JButton b_davincicode;
    private javax.swing.JButton b_delibal;
    private javax.swing.JButton b_frankestein;
    private javax.swing.JButton b_interstellar;
    private javax.swing.JButton b_jaws;
    private javax.swing.JButton b_strangerthings;
    private javax.swing.JButton b_theoriginals;
    private javax.swing.JLabel bizihatirla;
    private javax.swing.JLabel criminal;
    private javax.swing.JLabel dangal;
    private javax.swing.JLabel davincicode;
    private javax.swing.JLabel delibal;
    private javax.swing.JLabel frankestein;
    private javax.swing.JLabel interstellar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jaws;
    private javax.swing.JLabel strangerthings;
    private javax.swing.JLabel theblacklist;
    private javax.swing.JLabel theoriginals;
    // End of variables declaration//GEN-END:variables
}
