/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package berkay;



import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;


/**
 *
 * @author Berkay
 */
public class search extends javax.swing.JFrame {

    /**
     * Creates new form search
     */
    public search() {
        initComponents();
    }
   
    static final String JDBC_DRIVER="com.mysql.jdbc.Driver";
    static final String DOMAIN_NAME="root";
    static final String DB_NAME="project";
    static final String DB_URL="jdbc:mysql://"+DOMAIN_NAME+"/"+DB_NAME;
    static final String USER="root";
    static final String PASS="";
    
      ArrayList<Integer> pid_a=new ArrayList<Integer>();
      ArrayList<Integer> pid_a_temp=new ArrayList<Integer>();
      
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setText("ARA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Film,dizi veya istediğiniz bir tür adı ile arama yapabilirsiniz...(Tür İsimlerini Eksiksiz Girdiğinizden Emin Olun)");

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setText("İZLEMEK İÇİN ARAMA YAPTIKTAN SONRA ÇIKAN RESİMLERE TIKLAMANIZ YETERLİ OLACAKTIR.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(87, 87, 87)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> img=new ArrayList<String>();
        
        
        img.add("arifv216.jpg");
        img.add("atiye.jpg");
        img.add("cutestanimal.jpg");
        img.add("dreambig.jpg");
        img.add("harrypotter.jpg");
        img.add("howimet.jpg");
        img.add("ironfist.jpg");
        img.add("jurassic.jpg");
        img.add("kardesimbenim.jpg");
        img.add("leylailemecnun.jpg");
        img.add("lorofring.jpg");
        img.add("mask.jpg");
        img.add("missionblue.jpg");
        img.add("pandemic.jpg");
        img.add("plasticocean.jpg");
        img.add("recepivedik.jpg");
        img.add("scobdydoo.png");
        img.add("sherlock.jpg");
        img.add("shrek.jpg");
        img.add("sirinler.jpg");
        img.add("spiderman.jpg");
        img.add("interstellar.jpg");
        img.add("bizihatırla.jpg");
        img.add("delibal.jpg");
        img.add("dangal.jpg");
        img.add("jaws.jpg");
        img.add("davincicode.jpg");
        img.add("criminal.jpg");
        img.add("theblacklist.jpg");
        img.add("frankestein.jpg");
        img.add("strangerthings.jpg");
        img.add("theoriginal.jpg");
       
        
        String s=search.getText();
        Connection conn=null;
        ArrayList<JLabel> jl=new ArrayList<JLabel>();
        jl.add(jLabel2);
        jl.add(jLabel3);
        jl.add(jLabel4);
        jl.add(jLabel5);
        jl.add(jLabel6);
        jl.add(jLabel7);
        String sql="SELECT pid from project.program_table where p_name=?";
        String query="SELECT tid from project.type_table where type_name=?";
        String query2="Select pid from project.program_type where tid=?";
        int id=0;
        int tid=0;
        int pid=0;
        int control=0;
        ArrayList<String> type =new ArrayList<String>();
        type.add("Aksiyon"); type.add("Belgesel"); type.add("Bilim Kurgu ve Fantastik Yapımlar"); type.add("Bilim ve Doğa"); type.add("Çocuk ve Aile"); type.add("Dramalar"); type.add("Gerilim"); type.add("Komedi"); type.add("Korku");type.add("Romantizm");
        if(type.contains(search.getText())){
            control++;
            
        }
        Image img3=new ImageIcon(this.getClass().getResource("dark.png")).getImage();
        for(int i=0;i<6;i++){
                
                jl.get(i).setIcon(new ImageIcon(img3));
                
                
            }
        
        try {
        if(control==0){  
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);   
        PreparedStatement psmt=conn.prepareStatement(sql);
        psmt.setString(1,search.getText());
        ResultSet rs=psmt.executeQuery();
        if(rs.next()){
            id=rs.getInt("pid");
        }
            System.out.println(rs.getInt("pid"));
            Image img4=new ImageIcon(this.getClass().getResource(img.get(id))).getImage();
            jLabel2.setIcon(new ImageIcon(img4));
        psmt.close();
        pid_a.add(id);
        }else{
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);   
        PreparedStatement psmt=conn.prepareStatement(query);
        psmt.setString(1,search.getText());
        ResultSet rs=psmt.executeQuery();
        if(rs.next()){
            tid=rs.getInt("tid");
        }
            System.out.println(tid);
        psmt.close();
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);   
        psmt=conn.prepareStatement(query2);
        psmt.setInt(1,tid);
        rs=psmt.executeQuery();
        for(int j=0;j<32;j++){
        if(rs.next()){
            pid=rs.getInt("pid");
            pid_a.add(pid);
        }else
        break;
        }   
            //System.out.println(pid_a.get(3));
            
           
            for(int j=0;j<pid_a.size();j++){
                System.out.println(pid_a.get(j));
            }
        if(pid_a.size()!=0){
            for(int i=0;i<pid_a.size();i++){
              
                Image img5 =new ImageIcon(this.getClass().getResource(img.get(pid_a.get(i)))).getImage();
                jl.get(i).setIcon(new ImageIcon(img5));
                    
                
                
            }
            
            
        }psmt.close();
      control=0;  }
        } catch (Exception e) {
        }
        
         pid_a_temp=(ArrayList)pid_a.clone();
         pid_a.clear();
         
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.out.println("ok");
        System.out.println(pid_a_temp.get(0));
        Connection conn=null;
        String sql="SELECT p_name,p_type FROM project.program_table where pid=?";
        String p_name=null;
        String p_type=null ;
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);   
        PreparedStatement psmt=conn.prepareStatement(sql);
        psmt.setInt(1,pid_a_temp.get(0));
        ResultSet rs=psmt.executeQuery();
         System.out.println("ok");
        if(rs.next()){
            p_name=rs.getString("p_name");
            p_type=rs.getString("p_type");
        }
        rs.close();
        }
        catch (Exception e) {
                
        }
          System.out.println(p_name);
            System.out.println(p_type);
        if(p_type.equals("Film")){
        Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_f wsf=new watch_screen_f();
        film_screen fs=new film_screen();
        fs.name_c.add(p_name);
        conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(0));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
            System.out.println(line);
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                System.out.println("j="+j);
                System.out.println(line);
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    System.out.println("kontrol");
                    System.out.println(pid);
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==pid_a_temp.get(0)){
                    System.out.println("giriyooo");
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsf.setVisible(true);
                    break;
                    
                }
                
                control1++;
             
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println("oldu");
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(0));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
                
                
                
            }
               
            } 
            
            
        } catch (Exception e) {
        }
            
            
        }
        else{
          Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_d wsd=new watch_screen_d();
        film_screen fs=new film_screen();
        fs.name_c.add(p_name);
        fs.dizi_time.add(40);
        fs.dizi_part.add(10);
        System.out.println("");
         conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(0));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
                System.out.println("Burda");
            System.out.println(line);
                System.out.println(sis.user.get(0));
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==pid_a_temp.get(0)){
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsd.setVisible(true);
                    break;
                    
                }
                
                control1++;
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(0));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
        
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
                
                
                
            }
               
            }
            
            
        } catch (Exception e) {
        }
        
        
            
            
            pid_a_temp.clear();
            
            
        }
            
            
        
        
       
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
       System.out.println("ok");
        System.out.println(pid_a_temp.get(1));
        Connection conn=null;
        String sql="SELECT p_name,p_type FROM project.program_table where pid=?";
        String p_name=null;
        String p_type=null ;
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);   
        PreparedStatement psmt=conn.prepareStatement(sql);
        psmt.setInt(1,pid_a_temp.get(1));
        ResultSet rs=psmt.executeQuery();
         System.out.println("ok");
        if(rs.next()){
            p_name=rs.getString("p_name");
            p_type=rs.getString("p_type");
        }
        rs.close();
        }
        catch (Exception e) {
                
        }
          System.out.println(p_name);
            System.out.println(p_type);
        if(p_type.equals("Film")){
        Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_f wsf=new watch_screen_f();
        film_screen fs=new film_screen();
        fs.name_c.add(p_name);
        conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(1));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
            System.out.println(line);
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                System.out.println("j="+j);
                System.out.println(line);
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    System.out.println("kontrol");
                    System.out.println(pid);
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==pid_a_temp.get(1)){
                    System.out.println("giriyooo");
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsf.setVisible(true);
                    break;
                    
                }
                
                control1++;
             
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println("oldu");
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(1));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
                
                
                
            }
               
            } 
            
            
        } catch (Exception e) {
        }
            
            
        }
        else{
          Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_d wsd=new watch_screen_d();
        film_screen fs=new film_screen();
        fs.name_c.add(p_name);
        fs.dizi_time.add(40);
        fs.dizi_part.add(10);
        System.out.println("");
         conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(1));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
                System.out.println("Burda");
            System.out.println(line);
                System.out.println(sis.user.get(0));
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==pid_a_temp.get(1)){
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsd.setVisible(true);
                    break;
                    
                }
                
                control1++;
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(1));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
        
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
                
                
                
            }
               
            }
            
            
        } catch (Exception e) {
        }
        
        
            
            
            pid_a_temp.clear();
            
            
        }
            
            
        
        
       
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
              System.out.println("ok");
        System.out.println(pid_a_temp.get(2));
        Connection conn=null;
        String sql="SELECT p_name,p_type FROM project.program_table where pid=?";
        String p_name=null;
        String p_type=null ;
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);   
        PreparedStatement psmt=conn.prepareStatement(sql);
        psmt.setInt(1,pid_a_temp.get(2));
        ResultSet rs=psmt.executeQuery();
         System.out.println("ok");
        if(rs.next()){
            p_name=rs.getString("p_name");
            p_type=rs.getString("p_type");
        }
        rs.close();
        }
        catch (Exception e) {
                
        }
          System.out.println(p_name);
            System.out.println(p_type);
        if(p_type.equals("Film")){
        Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_f wsf=new watch_screen_f();
        film_screen fs=new film_screen();
        fs.name_c.add(p_name);
        conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(2));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
            System.out.println(line);
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                System.out.println("j="+j);
                System.out.println(line);
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    System.out.println("kontrol");
                    System.out.println(pid);
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==pid_a_temp.get(2)){
                    System.out.println("giriyooo");
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsf.setVisible(true);
                    break;
                    
                }
                
                control1++;
             
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println("oldu");
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(2));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
                
                
                
            }
               
            } 
            
            
        } catch (Exception e) {
        }
            
            
        }
        else{
          Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_d wsd=new watch_screen_d();
        film_screen fs=new film_screen();
        fs.name_c.add(p_name);
        fs.dizi_time.add(40);
        fs.dizi_part.add(10);
        System.out.println("");
         conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(2));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
                System.out.println("Burda");
            System.out.println(line);
                System.out.println(sis.user.get(0));
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==pid_a_temp.get(2)){
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsd.setVisible(true);
                    break;
                    
                }
                
                control1++;
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(2));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
        
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
                
                
                
            }
               
            }
            
            
        } catch (Exception e) {
        }
        
        
            
            
            pid_a_temp.clear();
            
            
        }
            
            
        
        
       
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         System.out.println("ok");
        System.out.println(pid_a_temp.get(3));
        Connection conn=null;
        String sql="SELECT p_name,p_type FROM project.program_table where pid=?";
        String p_name=null;
        String p_type=null ;
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);   
        PreparedStatement psmt=conn.prepareStatement(sql);
        psmt.setInt(1,pid_a_temp.get(3));
        ResultSet rs=psmt.executeQuery();
         System.out.println("ok");
        if(rs.next()){
            p_name=rs.getString("p_name");
            p_type=rs.getString("p_type");
        }
        rs.close();
        }
        catch (Exception e) {
                
        }
          System.out.println(p_name);
            System.out.println(p_type);
        if(p_type.equals("Film")){
        Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_f wsf=new watch_screen_f();
        film_screen fs=new film_screen();
        fs.name_c.add(p_name);
        conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(3));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
            System.out.println(line);
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                System.out.println("j="+j);
                System.out.println(line);
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    System.out.println("kontrol");
                    System.out.println(pid);
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==pid_a_temp.get(3)){
                    System.out.println("giriyooo");
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsf.setVisible(true);
                    break;
                    
                }
                
                control1++;
             
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println("oldu");
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(3));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
                
                
                
            }
               
            } 
            
            
        } catch (Exception e) {
        }
            
            
        }
        else{
          Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_d wsd=new watch_screen_d();
        film_screen fs=new film_screen();
        fs.name_c.add(p_name);
        fs.dizi_time.add(40);
        fs.dizi_part.add(10);
        System.out.println("");
         conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(3));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
                System.out.println("Burda");
            System.out.println(line);
                System.out.println(sis.user.get(0));
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==pid_a_temp.get(3)){
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsd.setVisible(true);
                    break;
                    
                }
                
                control1++;
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(3));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
        
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
                
                
                
            }
               
            }
            
            
        } catch (Exception e) {
        }
        
        
            
            
            pid_a_temp.clear();
            
            
        }
            
            
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
         System.out.println("ok");
        System.out.println(pid_a_temp.get(4));
        Connection conn=null;
        String sql="SELECT p_name,p_type FROM project.program_table where pid=?";
        String p_name=null;
        String p_type=null ;
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);   
        PreparedStatement psmt=conn.prepareStatement(sql);
        psmt.setInt(1,pid_a_temp.get(4));
        ResultSet rs=psmt.executeQuery();
         System.out.println("ok");
        if(rs.next()){
            p_name=rs.getString("p_name");
            p_type=rs.getString("p_type");
        }
        rs.close();
        }
        catch (Exception e) {
                
        }
          System.out.println(p_name);
            System.out.println(p_type);
        if(p_type.equals("Film")){
        Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_f wsf=new watch_screen_f();
        film_screen fs=new film_screen();
        fs.name_c.add(p_name);
        conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(4));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
            System.out.println(line);
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                System.out.println("j="+j);
                System.out.println(line);
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    System.out.println("kontrol");
                    System.out.println(pid);
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==pid_a_temp.get(4)){
                    System.out.println("giriyooo");
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsf.setVisible(true);
                    break;
                    
                }
                
                control1++;
             
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println("oldu");
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(4));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
                
                
                
            }
               
            } 
            
            
        } catch (Exception e) {
        }
            
            
        }
        else{
          Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_d wsd=new watch_screen_d();
        film_screen fs=new film_screen();
        fs.name_c.add(p_name);
        fs.dizi_time.add(40);
        fs.dizi_part.add(10);
        System.out.println("");
         conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(4));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
                System.out.println("Burda");
            System.out.println(line);
                System.out.println(sis.user.get(0));
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==pid_a_temp.get(4)){
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsd.setVisible(true);
                    break;
                    
                }
                
                control1++;
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(4));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
        
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
                
                
                
            }
               
            }
            
            
        } catch (Exception e) {
        }
        
        
            
            
            pid_a_temp.clear();
            
            
        }
            
            
        
       
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
           System.out.println("ok");
        System.out.println(pid_a_temp.get(5));
        Connection conn=null;
        String sql="SELECT p_name,p_type FROM project.program_table where pid=?";
        String p_name=null;
        String p_type=null ;
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);   
        PreparedStatement psmt=conn.prepareStatement(sql);
        psmt.setInt(1,pid_a_temp.get(5));
        ResultSet rs=psmt.executeQuery();
         System.out.println("ok");
        if(rs.next()){
            p_name=rs.getString("p_name");
            p_type=rs.getString("p_type");
        }
        rs.close();
        }
        catch (Exception e) {
                
        }
          System.out.println(p_name);
            System.out.println(p_type);
        if(p_type.equals("Film")){
        Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_f wsf=new watch_screen_f();
        film_screen fs=new film_screen();
        fs.name_c.add(p_name);
        conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(5));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
            System.out.println(line);
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                System.out.println("j="+j);
                System.out.println(line);
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    System.out.println("kontrol");
                    System.out.println(pid);
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==pid_a_temp.get(5)){
                    System.out.println("giriyooo");
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsf.setVisible(true);
                    break;
                    
                }
                
                control1++;
             
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println("oldu");
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(5));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsf.setVisible(true);
                
                
                
            }
               
            } 
            
            
        } catch (Exception e) {
        }
            
            
        }
        else{
          Sign_In_Screen sis=new Sign_In_Screen();
        watch_screen_d wsd=new watch_screen_d();
        film_screen fs=new film_screen();
        fs.name_c.add(p_name);
        fs.dizi_time.add(40);
        fs.dizi_part.add(10);
        System.out.println("");
         conn=null;
        Statement st=null;
        String query="SELECT line FROM user_program";
        String query1="SELECT uid,pid FROM user_program";
        String query2="SELECT line FROM user_program ORDER BY line DESC LIMIT 1";
        String query3="insert into project.user_program(line,uid,pid,date,part) values(?,?,?,?,?)";
        String query4="SELECT uid,pid,time,part,line FROM user_program";
        int line= 0;
        int control=0;
        int control1=0;
        int uid=0;
        int pid=0;
        int time=0;
        int part=0;
        int line1=0;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query); 
            
            if(rs.next()){
            line=rs.getInt("line");
            control++;
             
            }
            st.close();
        } catch (Exception e) {
        }
        
        try {
            if(control==0){
             
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1, 0);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(5));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
            fs.part_a.add(1);
            fs.time_a.add(0);
            fs.line_c.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
            }else{
                
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            ResultSet rs=st.executeQuery(query2); 
                
            if(rs.next()){
            line=rs.getInt("line");
            }
            st.close();
                System.out.println("Burda");
            System.out.println(line);
                System.out.println(sis.user.get(0));
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            st=conn.createStatement();
            rs=st.executeQuery(query4);     
            for(int j=0;j<line+1;j++){
                
                if(rs.next()){
                    uid=rs.getInt("uid");
                    pid=rs.getInt("pid");
                    time=rs.getInt("time");
                    part=rs.getInt("part");
                    line1=rs.getInt("line");
                    
                }if(uid==sis.user.get(0)&&pid==pid_a_temp.get(5)){
                    fs.time_a.add(time);
                    fs.part_a.add(part);
                    fs.line_c.add(line1);
                    this.setVisible(false);
                    wsd.setVisible(true);
                    break;
                    
                }
                
                control1++;
                
            }  rs.close();
                
            if(control1==line+1){
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
            PreparedStatement psmt=conn.prepareStatement(query3);
            System.out.println(sis.user.get(0));
            psmt.setInt(1,line+1);
            psmt.setInt(2,sis.user.get(0));
            psmt.setInt(3,pid_a_temp.get(5));
            psmt.setString(4,"2020-05-24");
            psmt.setInt(5,1);
            int i=psmt.executeUpdate();
            System.out.println(i+"oluşturuldu");        
            conn.close();
        
            fs.line_c.add(line+1);
            fs.part_a.add(1);
            fs.time_a.add(0);
            this.setVisible(false);
            wsd.setVisible(true);
                
                
                
            }
               
            }
            
            
        } catch (Exception e) {
        }
        
        
            
            
            pid_a_temp.clear();
            
            
        }
            
            
        
        
       
    }//GEN-LAST:event_jLabel7MouseClicked
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
             //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
               
                new search().setVisible(true);
                
                
            }
        });
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
