/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package berkay;

import static berkay.watch_screen_f.USER;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author Berkay
 */
public class Sign_Up_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Sign_Up_Screen
     */
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DOMAIN_NAME = "root";
    static final String DB_NAME = "project";
    static final String DB_URL = "jdbc:mysql://" + DOMAIN_NAME + "/" + DB_NAME;
    static final String USER = "root";
    static final String PASS = "";
    ArrayList<String> type_control = new ArrayList<String>();
    ArrayList<Integer> tid=new ArrayList<Integer>();
    public static final ArrayList<Integer> enb1=new ArrayList<Integer>();
    public static final ArrayList<Integer> enb2=new ArrayList<Integer>();
    public static final ArrayList<Integer> enb3=new ArrayList<Integer>();

    public Sign_Up_Screen() {
        initComponents();
        ImageIcon img = new ImageIcon("C:\\Users\\Berkay\\Desktop\\berkay\\src\\berkay\\Netflix_logo_n.png");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        type_label = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        aksiyon = new javax.swing.JCheckBox();
        belgesel = new javax.swing.JCheckBox();
        bilimkurgu = new javax.swing.JCheckBox();
        bilimdoga = new javax.swing.JCheckBox();
        cocukveaile = new javax.swing.JCheckBox();
        drama = new javax.swing.JCheckBox();
        gerilim = new javax.swing.JCheckBox();
        komedi = new javax.swing.JCheckBox();
        korku = new javax.swing.JCheckBox();
        romantizm = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date_field = new javax.swing.JTextField();
        name_field = new javax.swing.JTextField();
        password_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1042, 617));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1042, 700));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/berkay/Netflix_logo_n.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        password_label.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        password_label.setForeground(new java.awt.Color(153, 0, 51));
        password_label.setText("Şifre:");

        email_label.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        email_label.setForeground(new java.awt.Color(153, 0, 51));
        email_label.setText("Email Adresi:");
        email_label.setName(""); // NOI18N

        type_label.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        type_label.setForeground(new java.awt.Color(153, 0, 51));
        type_label.setText("Beğendiğiniz 3 Adet Tür Seçiniz:");

        aksiyon.setBackground(new java.awt.Color(0, 0, 0));
        aksiyon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aksiyon.setForeground(new java.awt.Color(153, 0, 51));
        aksiyon.setText("Aksiyon");

        belgesel.setBackground(new java.awt.Color(0, 0, 0));
        belgesel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        belgesel.setForeground(new java.awt.Color(153, 0, 51));
        belgesel.setText("Belgesel");

        bilimkurgu.setBackground(new java.awt.Color(0, 0, 0));
        bilimkurgu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bilimkurgu.setForeground(new java.awt.Color(153, 0, 51));
        bilimkurgu.setText("Bilim Kurgu Ve Fantastik Yapımlar");

        bilimdoga.setBackground(new java.awt.Color(0, 0, 0));
        bilimdoga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bilimdoga.setForeground(new java.awt.Color(153, 0, 51));
        bilimdoga.setText("Bilim Ve Doğa");

        cocukveaile.setBackground(new java.awt.Color(0, 0, 0));
        cocukveaile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cocukveaile.setForeground(new java.awt.Color(153, 0, 51));
        cocukveaile.setText("Çocuk Ve Aile");

        drama.setBackground(new java.awt.Color(0, 0, 0));
        drama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        drama.setForeground(new java.awt.Color(153, 0, 51));
        drama.setText("Dramalar");

        gerilim.setBackground(new java.awt.Color(0, 0, 0));
        gerilim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gerilim.setForeground(new java.awt.Color(153, 0, 51));
        gerilim.setText("Gerilim");

        komedi.setBackground(new java.awt.Color(0, 0, 0));
        komedi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        komedi.setForeground(new java.awt.Color(153, 0, 51));
        komedi.setText("Komedi");

        korku.setBackground(new java.awt.Color(0, 0, 0));
        korku.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        korku.setForeground(new java.awt.Color(153, 0, 51));
        korku.setText("Korku");

        romantizm.setBackground(new java.awt.Color(0, 0, 0));
        romantizm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        romantizm.setForeground(new java.awt.Color(153, 0, 51));
        romantizm.setText("Romantizm");

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 51));
        jButton1.setText("ÜYE OL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Ad:");

        jLabel3.setFont(new java.awt.Font("Impact", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("Doğum Tarihi:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("YYYY-AA-GG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(459, 459, 459))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(type_label)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(drama)
                                .addGap(18, 18, 18)
                                .addComponent(gerilim)
                                .addGap(18, 18, 18)
                                .addComponent(bilimkurgu)
                                .addGap(18, 18, 18)
                                .addComponent(bilimdoga))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(aksiyon)
                                .addGap(18, 18, 18)
                                .addComponent(belgesel)
                                .addGap(18, 18, 18)
                                .addComponent(komedi)
                                .addGap(18, 18, 18)
                                .addComponent(korku)
                                .addGap(18, 18, 18)
                                .addComponent(romantizm)
                                .addGap(10, 10, 10)
                                .addComponent(cocukveaile))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(password_label)
                                .addComponent(email_label)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(44, 44, 44)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(email_field)
                                .addComponent(date_field, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                .addComponent(name_field, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                .addComponent(password_field)))))
                .addGap(0, 194, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_label))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_label)
                    .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_field, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(type_label)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aksiyon)
                    .addComponent(belgesel)
                    .addComponent(komedi)
                    .addComponent(korku)
                    .addComponent(romantizm)
                    .addComponent(cocukveaile))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drama)
                    .addComponent(gerilim)
                    .addComponent(bilimkurgu)
                    .addComponent(bilimdoga))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        String sql = "insert into project.users(uid,u_name,u_mail,u_pass,u_date) values(?,?,?,?,?)";
        Statement st = null;
        String query = "SELECT uid FROM users ORDER BY uid DESC LIMIT 1";
        int bug=0;
        int id = 0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC", USER, PASS);
            st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);
            if (rs.next()) {

                id = rs.getInt("uid") + 1;

            } else {

                id = 0;

            }

            st.close();

        } catch (Exception e) {

        }

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC", USER, PASS);
            PreparedStatement psmt = conn.prepareStatement(sql);
            psmt.setInt(1, id);
            psmt.setString(2, name_field.getText());
            psmt.setString(3, email_field.getText());
            psmt.setString(4, password_field.getText());
            psmt.setString(5, date_field.getText());
            int i = psmt.executeUpdate();
            System.out.println(i + "oluşturuldu");
            conn.close();

        } catch (SQLException se) {
            Entery_Screen es=new  Entery_Screen();
            JOptionPane.showMessageDialog(null, "Girmiş Olduğunuz Bilgiler Hatalı veya Eposta Sistemde Kayıtlı...");
            this.setVisible(false);
            bug++;
            es.setVisible(true);
            se.printStackTrace();
            
        } catch (Exception e) {
            Entery_Screen es=new  Entery_Screen();
            JOptionPane.showMessageDialog(null, "Girmiş Olduğunuz Bilgiler Hatalı veya Eposta Sistemde Kayıtlı...");
            es.setVisible(true);
            bug++;
            e.printStackTrace();
        }

        if (aksiyon.isSelected()) {

            type_control.add("Aksiyon");

        } else {
            type_control.remove("Aksiyon");
        }
        if (belgesel.isSelected()) {

            type_control.add("Belgesel");

        } else {
            type_control.remove("Belgesel");
        }
        if (komedi.isSelected()) {

            type_control.add("Komedi");

        } else {
            type_control.remove("Komedi");
        }
        if (korku.isSelected()) {

            type_control.add("Korku");

        } else {
            type_control.remove("Korku");
        }
        if (romantizm.isSelected()) {

            type_control.add("Romantizm");

        } else {
            type_control.remove("Romantizm");
        }
        if (cocukveaile.isSelected()) {

            type_control.add("Çocuk ve Aile");

        } else {
            type_control.remove("Çocuk ve Aile");
        }
        if (drama.isSelected()) {

            type_control.add("Dramalar");

        } else {
            type_control.remove("Dramalar");
        }
        if (gerilim.isSelected()) {

            type_control.add("Gerilim");

        } else {
            type_control.remove("Gerilim");
        }
        if (bilimkurgu.isSelected()) {

            type_control.add("Bilim Kurgu ve Fantastik Yapımlar");

        } else {
            type_control.remove("Bilim Kurgu ve Fantastik Yapımlar");
        }
        if (bilimdoga.isSelected()) {

            type_control.add("Bilim ve Doğa");

        } else {
            type_control.remove("Bilim ve Doğa");
        }

        
        
        if (type_control.contains("Aksiyon")) {
            tid.add(0);
        }
        if (type_control.contains("Belgesel")) {
             tid.add(1);
        }
        if (type_control.contains("Bilim Kurgu ve Fantastik Yapımlar")) {
            tid.add(2);
        }
        if (type_control.contains("Bilim ve Doğa")) {
            tid.add(3);
        }
        if (type_control.contains("Çocuk ve Aile")) {
             tid.add(4);
        }
        if (type_control.contains("Dramalar")) {
             tid.add(5);
        }
        if (type_control.contains("Gerilim")) {
             tid.add(6);
        }
        if (type_control.contains("Komedi")) {
             tid.add(7);
        }
        if (type_control.contains("Korku")) {
            tid.add(8);
        }
        if (type_control.contains("Romantizm")) {
           tid.add(9);
        }
        if(bug==0){
        ArrayList<Integer> pid1=new ArrayList<Integer>();
        ArrayList<Integer> pid2=new ArrayList<Integer>();
        ArrayList<Integer> pid3=new ArrayList<Integer>();
        ArrayList<String> rate_a1=new ArrayList<String>();
        ArrayList<String> rate_a2=new ArrayList<String>();
        ArrayList<String> rate_a3=new ArrayList<String>();
        ArrayList<Integer> total1=new ArrayList<Integer>();
        ArrayList<Integer> total2=new ArrayList<Integer>();
        ArrayList<Integer> total3=new ArrayList<Integer>();
        conn=null;
        String query3="select pid from project.program_type where tid=?";
        try {    
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
        PreparedStatement psmt=conn.prepareStatement(query3);
        psmt.setInt(1,tid.get(0));
        ResultSet rs=psmt.executeQuery();
        for(int i=0;i<56;i++){
        if(rs.next()){
            pid1.add(rs.getInt("pid"));
        }else{
            break;
        }
        }rs.close();
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
        psmt=conn.prepareStatement(query3);
        psmt.setInt(1,tid.get(1));
        rs=psmt.executeQuery();
        for(int i=0;i<56;i++){
        if(rs.next()){
            pid2.add(rs.getInt("pid"));
        }else{
            break;
        }
        }rs.close();
           
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
        psmt=conn.prepareStatement(query3);
        psmt.setInt(1,tid.get(2));
        rs=psmt.executeQuery();
        for(int i=0;i<56;i++){
        if(rs.next()){
            pid3.add(rs.getInt("pid"));
        }else{
            break;
        }
        }
        rs.close();
        for(int j=0;j<pid1.size();j++){
            System.out.println(pid1.get(j));
            
        }
        for(int j=0;j<pid2.size();j++){
            System.out.println(pid2.get(j));
            
        }
        for(int j=0;j<pid3.size();j++){
            System.out.println(pid3.get(j));
            
        }
        
                
        
        
        } catch (Exception e) {
        }
        for(int i=0;i<pid1.size();i++){
        int bug_fix=0;
        conn=null;
        String query4="select rate from project.user_program where pid=?";
            try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
        PreparedStatement psmt=conn.prepareStatement(query4);
        psmt.setInt(1,pid1.get(i));
        ResultSet rs=psmt.executeQuery();
        for(int j=0;j<100;j++){
        if(rs.next()){
           int a= rs.getInt("rate");
           rate_a1.add(Integer.toString(a));
           bug_fix++;
        }else{
            break;
        }
        }
        if(bug_fix>0){
        rate_a1.add("a");
        }
        bug_fix=0;
        rs.close();
                
                
            } catch (Exception e) {
            }
            
            
        }
         for(int i=0;i<pid2.size();i++){
        int bug_fix=0;
        conn=null;
        String query4="select rate from project.user_program where pid=?";
            try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
        PreparedStatement psmt=conn.prepareStatement(query4);
        psmt.setInt(1,pid2.get(i));
        ResultSet rs=psmt.executeQuery();
        for(int j=0;j<100;j++){
        if(rs.next()){
           int a= rs.getInt("rate");
           rate_a2.add(Integer.toString(a));
           bug_fix++;
        }else{
            break;
        }
        }
        if(bug_fix>0){
        rate_a2.add("a");
        }
        bug_fix=0;
        rs.close();
                
                
            } catch (Exception e) {
            }
            
            
        }
         System.out.println("pid2:");
         for (int i = 0; i < pid2.size(); i++) {
             System.out.println(pid2.get(i));
        }
            System.out.println("pid3");
            for (int i = 0; i < pid3.size(); i++) {
             System.out.println(pid3.get(i));
        }
         
        for(int i=0;i<pid3.size();i++){
        int bug_fix=0;
        conn=null;
        String query4="select rate from project.user_program where pid=?";
            try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn=DriverManager.getConnection("jdbc:mysql://localhost/project?useLegacyDatetimeCode=false&serverTimezone=UTC",USER,PASS);    
        PreparedStatement psmt=conn.prepareStatement(query4);
        psmt.setInt(1,pid3.get(i));
        ResultSet rs=psmt.executeQuery();
        for(int j=0;j<100;j++){
        if(rs.next()){
           int a= rs.getInt("rate");
           rate_a3.add(Integer.toString(a));
           bug_fix++;
        }else{
            break;
        }
        }
        if(bug_fix>0){
        rate_a3.add("a");
        }
        bug_fix=0;
        rs.close();
                
                
            } catch (Exception e) {
            }
            
            
        }
        int avarage=0;
        int total=0;
        String s="a";
        for(int i=0;i<rate_a1.size();i++){
            
            if(rate_a1.get(i)!=s){
              total=Integer.parseInt(rate_a1.get(i))+total;
              avarage++;
                
            }else{
                System.out.println("x");
                System.out.println(avarage);
                total1.add(total/avarage);
                avarage=0;
                total=0;
                
            }
            
            
            
        }
         for(int i=0;i<rate_a2.size();i++){
            
            if(rate_a2.get(i)!=s){
                System.out.println("ok");
              total=  Integer.parseInt(rate_a2.get(i))+total;
              avarage++;
                
            }else{
                System.out.println("y");
                System.out.println(avarage);
                total2.add(total/avarage);
                avarage=0;
                total=0;
                
            }
            
            
            
        }
            
         
          for(int i=0;i<rate_a3.size();i++){
            
            if(rate_a3.get(i)!=s){
              total=  Integer.parseInt(rate_a3.get(i))+total;
              avarage++;
                System.out.println("giriyo");  
            }else{
                
                System.out.println("z");
                System.out.println(avarage);
                total3.add(total/avarage);
                avarage=0;
                total=0;
                
            }
            
            
            
        }
         
         int e1=total1.get(0);
         int e1_1=total1.get(0);
         int i1=0;
         int e2=total2.get(0);
         int e2_2=total2.get(0);
         int i2=0;
         int e3=total3.get(0);
         int e3_3=total3.get(0);
         int i3=0;
        for(int i=0;i<total1.size();i++){
            
            //System.out.println(total1.get(i));
            for(int j=0;j<total1.size();j++){
                if(e1<total1.get(j)){
                    
                    e1=total1.get(j);
                    i1=j;
                }
                 
            }
            
        }
        System.out.println(e1);
        System.out.println(total1.size());
        System.out.println("evet");
        enb1.add(pid1.get(i1));
        total1.remove(i1);
        System.out.println(total1.size());
          for(int i=0;i<total1.size();i++){
            System.out.println("2------");
            //System.out.println(total1.get(i));
            for(int j=0;j<total1.size();j++){
                System.out.println("size:");
                System.out.println(total1.size());
                if(e1_1<total1.get(j)){
                    if(enb1.get(0)==pid1.get(j)){
                        //total1.remove(j);
                        
                    }else{
                        
                    e1_1=total1.get(j);
                    i1=j;
                    }
                }
                 
            }
            
        }
          enb1.add(pid1.get(i1));
          System.out.println("2------");
          
         for(int i=0;i<total2.size();i++){
            
            //System.out.println(total2.get(i));
             for(int j=0;j<total2.size();j++){
                if(e2<total2.get(j)){
                    if(enb1.get(0)==pid2.get(j)||enb1.get(1)==pid2.get(j)){
                        //total2.remove(j);
                        
                    }else{
                        System.out.println(j);
                    e2=total2.get(j);
                    i2=j;
                    }
                }
                 
            }
            
        }
         enb2.add(pid2.get(i2));
         total2.remove(i2);
         for(int i=0;i<total2.size();i++){
            
            //System.out.println(total2.get(i));
             for(int j=0;j<total2.size();j++){
                if(e2_2<total2.get(j)){
                    System.out.println("enb2="+enb2.get(0));
                    System.out.println("j="+j);
                    if(enb1.get(0)==pid2.get(j)||enb1.get(1)==pid2.get(j)||enb2.get(0)==pid2.get(j)){
                        System.out.println("--------");
                        //total2.remove(j);
                        
                    }else{
                        System.out.println(j);
                    e2_2=total2.get(j);
                    i2=j;
                    
                    }
                }
                 
            }
            
        }
         enb2.add(pid2.get(i2));
         
          for(int i=0;i<total3.size();i++){
            
            //System.out.println(total3.get(i));
              for(int j=0;j<total3.size();j++){
                if(e3<total3.get(j)){
                    if(enb1.get(0)==pid3.get(j)||enb1.get(1)==pid3.get(j)||enb2.get(0)==pid3.get(j)||enb2.get(1)==pid3.get(j)){
                        //total3.remove(j);
                        
                    }else{
                    e3=total3.get(j);
                    i3=j;
                    }
                }
                 
            }
            
        }enb3.add(pid3.get(i3));
         total3.remove(i3);
         for(int i=0;i<total3.size();i++){
            
            //System.out.println(total3.get(i));
              for(int j=0;j<total3.size();j++){
                if(e3_3<=total3.get(j)){
                    if(enb1.get(0)==pid3.get(j)||enb1.get(1)==pid3.get(j)||enb2.get(0)==pid3.get(j)||enb2.get(1)==pid3.get(j)||enb3.get(0)==pid3.get(j)){
                        //total3.remove(j);
                        
                    }else{
                    e3_3=total3.get(j);
                    i3=j;
                    }
                }
                 
            }
            
        }enb3.add(pid3.get(i3));
        System.out.println("bura:");
        System.out.println(enb1.get(0));
        System.out.println(enb1.get(1));
        System.out.println(enb2.get(0));
        System.out.println(enb2.get(1));
        System.out.println(enb3.get(0));
        System.out.println(enb3.get(1));
        
        
        offer_screen os=new offer_screen();
        this.setVisible(false);
        os.setVisible(true);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_Up_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_Up_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_Up_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_Up_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Up_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aksiyon;
    private javax.swing.JCheckBox belgesel;
    private javax.swing.JCheckBox bilimdoga;
    private javax.swing.JCheckBox bilimkurgu;
    private javax.swing.JCheckBox cocukveaile;
    private javax.swing.JTextField date_field;
    private javax.swing.JCheckBox drama;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel email_label;
    private javax.swing.JCheckBox gerilim;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox komedi;
    private javax.swing.JCheckBox korku;
    private javax.swing.JTextField name_field;
    private javax.swing.JTextField password_field;
    private javax.swing.JLabel password_label;
    private javax.swing.JCheckBox romantizm;
    private javax.swing.JLabel type_label;
    // End of variables declaration//GEN-END:variables
}
